// src/components/employees.js

export const employees = [
    {
      EmployeeId: 1,
      EmpName: "John Doe",
      Department: "IT",
      Salary: 50000,
      PhoneNumber: "123-456-7890",
      EmailId: "john.doe@example.com",
      Address: "123 Main St, City",
      State: "CA",
    },
    {
      EmployeeId: 2,
      EmpName: "Jane Smith",
      Department: "HR",
      Salary: 60000,
      PhoneNumber: "987-654-3210",
      EmailId: "jane.smith@example.com",
      Address: "456 Elm St, Town",
      State: "NY",
    },
    {
      EmployeeId: 3,
      EmpName: "Michael Johnson",
      Department: "Finance",
      Salary: 70000,
      PhoneNumber: "555-123-4567",
      EmailId: "michael.johnson@example.com",
      Address: "789 Oak Ave, Village",
      State: "TX",
    },
    {
      EmployeeId: 4,
      EmpName: "Emily Brown",
      Department: "Marketing",
      Salary: 55000,
      PhoneNumber: "333-987-6543",
      EmailId: "emily.brown@example.com",
      Address: "101 Pine Rd, Town",
      State: "FL",
    },
    {
      EmployeeId: 5,
      EmpName: "William Lee",
      Department: "IT",
      Salary: 60000,
      PhoneNumber: "777-456-1234",
      EmailId: "william.lee@example.com",
      Address: "321 Cedar St, City",
      State: "CA",
    },
    {
      EmployeeId: 6,
      EmpName: "Sophia Taylor",
      Department: "HR",
      Salary: 65000,
      PhoneNumber: "222-333-4444",
      EmailId: "sophia.taylor@example.com",
      Address: "456 Elm St, Town",
      State: "NY",
    },
    {
      EmployeeId: 7,
      EmpName: "Daniel Clark",
      Department: "Finance",
      Salary: 72000,
      PhoneNumber: "111-222-3333",
      EmailId: "daniel.clark@example.com",
      Address: "789 Oak Ave, Village",
      State: "TX",
    },
    {
      EmployeeId: 8,
      EmpName: "Olivia Moore",
      Department: "Marketing",
      Salary: 58000,
      PhoneNumber: "666-555-4444",
      EmailId: "olivia.moore@example.com",
      Address: "101 Pine Rd, Town",
      State: "FL",
    },
    
  ];
  